In [4]:
# write a triengle to find a area of a trinagle
# area of triangel = 1/2base*height
base = float(input("enter base value : "))
height = float(input("enter height value : "))
area = 0.5*base*height
print(f"area of tringle is {area}")

enter base value : 12.5
enter height value : 9.7
area of tringle is 60.62499999999999

In [9]:
#write a python program to swap to numbers
a = input("entere your first value: ")
b = input("enter your second value: ")
print(f"before swqaping numbers value of a is : {a} and value od b is : {b}")
x = a
a = b
b = a
print(f"after swaping value of a is : {a} and b is : {b}")

entere your first value: 13
enter your second value: 31
before swqaping numbers value of a is : 13 and value od b is : 31
after swaping value of a is : 31 and b is : 31

In [10]:
# # write a program to generate a random number
# to genearet a random number we need to import randommodule
import random
print(random.randint(0,9))

7

In [12]:
# write a program to convert kilometer to miles
KM = float(input("enter your value in kilometers : "))
miles = KM*0.621371
print(f"{KM} kilometers are {miles} in  miles ")

enter your value in kilometers : 12
12.0 kilometers are 7.4564520000000005 in  miles

In [15]:
# write a proigram to convert celsius in to farenheit
# Conversion formula: Fahrenheit = (Celsius * 9/5) + 32
cel = float(input("enter your temp in celsius: "))
far = (cel * 9/5) + 32
print(f"{cel} celsius are {far} in farenheit")


# fahrenheight to celsius
far = float (input("enter your temprature in farenheit :"))
cel = (far - 32)*5/9
print(f"{far} farenheit are {cel} in celsius")

enter your temp in celsius: 33
33.0 celsius are 91.4 in farenheit
enter your temprature in farenheit :91.3
91.3 farenheit are 32.94444444444444 in celsius

In [24]:
# write a program to show calender
# for showinr calender we need to impoer t calender first
import calendar
year = int(input("enter your year  :"))
month = int(input('enter your month :'))
cal = calendar.month(year,month)
print(cal)

enter your year  :2024
enter your month :12
   December 2024
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30 31

In [25]:
# write a program to swap two varibles without ussing third vars
a  = int (input("enter your value "))
b   = int(input("enter your value "))
a, b = b, a
# after swaping  /
print(f"vlue of a is {a}")
print(f"value of b is {b}")

enter your value 13
enter your value 31
vlue of a is 31
value of b is 13

In [29]:
# check the given number is positive , negative or neutral
a = int(input("enter your numbe r here : "))
if a> 0:
  print(f"{a} is a +tive value")
elif a<0:
  print(f"{a} is a -tive value")
else:
  print(f"{a} is a neutral value")

enter your numbe r here : 0
0 is a neutral value

In [31]:
# write a number to check given year is leap year or not
year = int(input("enter your year here : "))
if (year%400 == 0 and year%100 ==0) or (year%4== 0 and year%100 != 0):
  print(f"{year} is a leap year")
else:
  print(f"{year} is not a leap year")

enter your year here : 2013
2013 is not a leap year